name: Bartosz CI/CD pipeline

on:
    push:
      branches:
        - main
    pull_request:

jobs:
  bartosz:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]

    permissions:
      checks: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4